### PR TITLE
Change order of icons, support for bootstrap

### PR DESCRIPTION
**Pull request by tekstrand**
#2 

Also adds support for bootstrap theme using bootstrap icons

### CODE REVIEW

**Comment by ramack** [comment]
Thanks for your efforts

**Comment by ramack** [comment]
Today I tried it with the bootstrap-darkroom theme and the rotate icons are not shown... Which versions (piwigo and theme) did you use for testing? and which theme exactly did you use?

**Comment by tekstrand** [comment]
I used the most recent version of bootstrap-darkroom. When you say that they didn't show, do you mean they icons failed to load(empty squares would show instead) or that no icons showed up at all?

**Comment by ramack** [comment]
In "Bootstrap" I see a box and a space...
In "Bootstrap Darkroom" I do not even see empty squares...

**Comment by tekstrand** [comment]
It's theoretically possible that the version you're using does not have those fontawesome icons, do you know which version of the themes you have?

**Comment by ramack** [comment]
tss.. this sounds more easy than it is. - I am too dumb to find where piwigo is showing it's own version. In the code I see:
Theme Name: Bootstrap Default
Version: 1.0.7

Theme Name: Bootstrap Darkroom
Version: 2.4.1

'PHPWG_VERSION', '2.9.5'

And obviously the modus theme I installed to step into #1 is using font based icons... Not sure whether this is what is understood as fontawesome icons though.

**Comment by tekstrand** [comment]
I have those versions as well. I was able to replicate the issue on bootstrap default. We could switch back to the previous icons, it doesn't look like bootstrap-default support font awesome, only the old glyphicons(https://getbootstrap.com/docs/3.3/components/) which doesn't have any good options for what we want. Preference?

**Pull request merged**
