### PR TITLE
Add missing i18n message and unify error display

### PR DESCRIPTION
**Pull request by samwilson**
Add the missing message about requiring the imageRotate plugin,
and merge the two places in which this error message is added.

### CODE REVIEW

**Review by tekstrand — APPROVED** [review]
Looks like the maintainer may not be around, but code LGTM

**Comment by ramack** [comment]
Sorry for not responding. I was on vacation and still did not finish to work through my inbox 😪 thanks @tekstrand for the review I'll merge it later.
In case one of you have an idea how to address one of the open issues, let me know. Otherwise I'll try to do a release soon...

**Comment by tekstrand** [comment]
👍 I swapped the order of the rotate buttons, I wasn't able to replicate #4 but I will say the plugin is not working for me.

**Comment by ramack** [comment]
> +1 I swapped the order of the rotate buttons, I wasn't able to replicate #4 but I will say the plugin is not working for me.

**not** working for you? Or is it working?

**Comment by tekstrand** [comment]
*not* working currently. #7

**Comment by samwilson** [comment]
Thanks both of you.

**Pull request merged**
